### ISSUE TITLE
configuration flag seems to be ignored

### ISSUE THREAD

**Issue by michaeljota** [meltedspark/angular-builders#102]
**Describe the bug**

When setting a configuration key in the `angular.json` the CLI seems to ignore all the options set inside of a configuration. 

**To Reproduce**
1. Setup a configuration in the `angular.json` file.
2. run `ng test --configuration=my-configuration`

**Expected behavior**

The options set in my-configuration should be used. 

**Screenshots**

**Builder:**
 - `@angular-builders/jest`
 - `1.2.5`

**Libraries**
```
    "@angular-devkit/build-angular": "0.8.4",
    "@angular-devkit/core": "0.8.4",
    "@angular/cli": "6.2.4",
    "@angular/compiler-cli": "~6.1.9",
```

**Additional context**

**Comment by meltedspark** [comment]
Adding the following in the test section of the [example project](https://github.com/meltedspark/angular-builders/tree/master/packages/jest/examples/simple-app) works for me:

	  "configurations": {
            "my-config": {
              "testNamePattern": "AppComponent should create the app"
            }
      }

Would you mind creating a sample project that demonstrates your issue?

**Comment by meltedspark** [comment]
Closed for inactivity
