### ISSUE TITLE
Where to find webpack config for default builders?

### ISSUE THREAD

**Issue by bjolletz** [meltedspark/angular-builders#15]
Hi!

This looks all really good and nicely configurable. But where can I find the webpack configurations for the default builders? I suppose the purpose of the custom builders is to be able to make customisations to the default builders, but it's kind of hard to customise a builder when you can not see it anywhere :)

Thanks in advance!

**Comment by meltedspark** [comment]
Unfortunately it's not that easy, I gave some clue in #14. Anyways, there is an ongoing development to allow merging plugins configuration (which is what you need I assume). This way you won't have to specify all the original configuration along with the new one, but only the parts you'd like to modify.

**Comment by bjolletz** [comment]
Thanks, the links in that case were helpful. I wish there would have been a way to export the resulting webpack configs for different builders, something like ng eject in Angular<=5. Then it would be easier to know how to create a modification in a custom builder.
