### ISSUE TITLE
Whitelisting lodash-es using nodeExternals not working

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [meltedspark/angular-builders#158]
**Describe the bug**

I am using lodash-es in my Angular project and want to use Universal in this project. I faced issues in this regard
```
node_modules\lodash-es\cloneDeep.js:1
(function (exports, require, module, __filename, __dirname) { import baseClone from './_baseClone.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.lodash-es/cloneDeep (G:\Work\MEAN\elitebgs\dist\server\main.js:10379:18)
```
which is expected since lodash-es is, well, ES and I need a commonJS build. As such I found that whitelisting lodash-es with `webpack-node-externals` would fix this. As such I modified the angular.json
```
"architect": {
    "server": {
      "builder": "@angular-builders/custom-webpack:server",
      "options": {
        "customWebpackConfig": {
          "path": "./universal-webpack.config.js",
          "mergeStrategies": { "loaders": "replace" }
        },
        "outputPath": "dist/server",
        "main": "src/main.server.ts",
        "tsConfig": "src/tsconfig.server.json"
      }
    }
```
and the custom webpack is
```
const nodeExternals = require('webpack-node-externals');

module.exports = {
    externals: [
        nodeExternals({
            whitelist: [/^lodash-es/]
        })
    ]
}
```
But this does not change the main.js that is built nor is the above error message.
**To Reproduce**
See above

**Expected behavior**
I expect for Angular Universal to work fine with lodash-es as a dependency.

**Builder:**
 - @angular-builders/custom-webpack
 - 7.0.0

**Libraries**
 - `angular-devkit/build-angular`: 0.11.0

**Additional context**
If you need any more information, I will gladly give them

**Comment by meltedspark** [comment]
I don't think you need this at all since you're in Typescript. Are you using `@types/lodash-es` along with `lodash-es`?

**Comment by SayakMukhopadhyay** [comment]
Well, that's embarrassing. I have been at for half a week and almost decided to move all 45 components of my app to Vue and it all boils down to the incorrect merge merge object.
Yup, `"mergeStrategies": { "externals": "replace" }` fixed it.
Thanks a lot for looking into this.
