### ISSUE TITLE
ng-annotate-loader Typescript processing order

### ISSUE THREAD

**Issue by nandastone** [meltedspark/angular-builders#186]
**Describe the bug**
I'm upgrading an AngularJS 1.6 project with *ngUpgrade* to run both ng+ and AngularJS code in the same project.

The AngularJS code requires *ng-annotate-loader* for DI annotations.

*ng-annotate-loader* should run AFTER the Angular CLI webpack rules have parsed TypeScript, as *ng-annotate-loader* cannot parse TypeScript.

**angular.json**
```
"customWebpackConfig": {
  "path": "src/extra-webpack.config.ts"
},
```

**webpack.config.ts**
```
const path = require('path');

module.exports = {
  // @todo ng-annotate-loader is trying to annotate TypeScript before it has been processed by ts-loader.
  module: {
    rules: [
      {
        // Do we target TypeScript that has been processed by ts-loader?
        test: /\.ts?$/,
        // Or do we somehow target JS after ts-loader has finished processing?
        // test: /\.js?$/,
        // Only parse the AngularJS scripts (that require DI annotations).
        include: [
          path.resolve(__dirname, 'legacy'),
        ],
        use: [
          {
            loader: 'ng-annotate-loader',
            options: {
              ngAnnotate: 'ng-annotate-patched',
            }
          },
        ]
      },
    ]
  }
};
```

Error:

```
ERROR in ./src/legacy/shared/components/app-version/app-version.component.ts
Module build failed (from ./node_modules/ng-annotate-loader/loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) error: couldn't process source due to parse error,Unexpected token (5:25)
    at runLoaders (/Users/mastone/Work/Everwealth.WebAppMigration/node_modules/webpack/lib/NormalModule.js:283:13)
    at /Users/mastone/Work/Everwealth.WebAppMigration/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mastone/Work/Everwealth.WebAppMigration/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at Object.context.callback (/Users/mastone/Work/Everwealth.WebAppMigration/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/mastone/Work/Everwealth.WebAppMigration/node_modules/ng-annotate-loader/loader.js:87:10)
```

**To Reproduce**

*OR (preferred way)*

 a link to a repository with minimal reproduction

**Expected behavior**

**Screenshots**

**Builder:**
 - The name of the builder
 - The version of the builder

**Libraries**
```
"@angular-builders/custom-webpack": "^7.1.1",
"@angular-builders/dev-server": "^7.1.1",
"@angular-devkit/build-angular": "^0.11.4",
"ng-annotate-loader": "^0.6.1",
"ng-annotate-patched": "^1.7.0",
```

**Additional context**

**Comment by meltedspark** [comment]
Hi,
Could you please try using merge strategy `"module.rules": "prepend"` or `"module": "prepend"` and update me on the result?

**Comment by nandastone** [comment]
@meltedspark Both options have solved my issue. I was trying to merge `loaders` as outlined in the documentation:

```
"mergeStrategies": { "loaders": "prepend" },
```

Thank you for your help!

**Comment by NitsanBaleli** [comment]
trying the exact same code as above results in a successful compilation, but no annotations are actually added to the compiled code.

is there anything more that needs to be done ?

**Comment by NitsanBaleli** [comment]
That fixed it for me aswell!
Question, is there a way have one loader (sass-loader) to not be "prepend" like the rest? I actually need that one to come first, as opposed to the ng-annotate-loader

**Comment by meltedspark** [comment]
You can use custom webpack config [function](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-function). This allows you to modify the webpack configuration as you please, in particular you can alter the loaders array by pushing one loader at the end and another at the beginning. Please let me know if it worked for you.

**Comment by NitsanBaleli** [comment]
@meltedspark Any such example by any chance? I'm trying to use webpack-merge inside the function still unsuccessfully. Will report here once I succeed.

**Comment by meltedspark** [comment]
Just directly access rules array and put the loaders you want there (inside the config function): `config module.rules.push(myLoader)`

**Comment by NitsanBaleli** [comment]
works as advertised :) thank you very much

**Comment by alexmacavei** [comment]
I'm running into issues with a similar setup. Did you have to instruct the ng-annotate loader to process .js or .ts files? The mergeStrategies option needs to be set in angular.json under the custom-webpack builder right?

**Comment by nbaleli-w** [comment]
@alexmacavei In my case, `ng-annotate-loader` was for `.ts` files.
and I didn't use the `mergeStrategies`, but followed the advice by @just-jeb here: https://github.com/just-jeb/angular-builders/issues/186#issuecomment-484035667

**Comment by NitsanBaleli** [comment]
@alexmacavei  In my case, `ng-annotate-loader` was for `.ts` files.
and I didn't use `mergeStrategies`, but followed the advice by @just-jeb b here: https://github.com/just-jeb/angular-builders/issues/186#issuecomment-484035667

**Comment by alexmacavei** [comment]
@NitsanBaleli Thanks, I'll give it a shot! Will get back with an answer.

**Comment by alexmacavei** [comment]
Hey!
My extended.webpack.config file is something like:
```
const path = require('path');
const webpack = require('webpack');

module.exports = (config) => {
  config.plugins.push(new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    'window.jQuery': 'jquery'
  }));
  config.module.rules.filter(rule => rule.test.test('.scss'))[0].exclude.push(path.resolve(__dirname, 'src/app/angularjs'));

  config.module.rules.push({
    test: /\.ts$/,
    include: path.resolve(__dirname, 'src/app/angularjs'),
    loader: 'ng-annotate-loader',
    options: { ngAnnotate: 'ng-annotate-patched', es6: true }
  }, {
    test: /\.html$/,
    use: ['raw-loader']
  }, {
    test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'file-loader'
  });

  return config;
};
```
Errors I'm getting are something like:
```
Module build failed (from ./node_modules/ng-annotate-loader/loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) error: couldn't process source due to parse error,Unexpected token (9:10)
```
Should ng-annotate run before Angular's webpack-loader ?
