### ISSUE TITLE
Add  instruction how to work with Jest VS code extension 

### ISSUE THREAD

**Issue by obsd** [meltedspark/angular-builders#213]
this is the extension orta.vscode-jest
And it seems to work without your configuration, if you can add instructions how to make it work, I will appreciate it.
Thanks

**Comment by meltedspark** [comment]
Well, I'm not sure what to tell... Could you elaborate please? What extension, what is the context? Does it work or it does not? What kind of instructions you'd like me to add?

**Comment by obsd** [comment]
thanks for the comment
https://github.com/jest-community/vscode-jest
this is the extension.
If we could use your great code with this package this will be cool, cause right now if I'm using your code, the extension is showing error about Zone.js

**Comment by meltedspark** [comment]
Would you mind creating a small reproduction repo so that I could identify the root cause ASAP? Thanks.

**Comment by mattwilson1024** [comment]
I'm not sure if this is relevant but if it helps but I found that to get the Jest VSCode plugin to play nicely with the builder I had to add the following workspace setting in VSCode:

`"jest.pathToJest": "ng test <project name>"`
