### ISSUE TITLE
Please could you do a new release of @angular-builders/custom-webpack to npm?

### ISSUE THREAD

**Issue by mattlewis92** [meltedspark/angular-builders#224]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the new `es5BrowserSupport` option from angular cli 7.3.0 but the current schema won't let me validate it, it looks like everything is in master and just cutting a new release will be enough to update the schema. Thanks for your time and for maintaining this really handy project! 😄

**Comment by meltedspark** [comment]
Done both for `custom-webpack` and `dev-server` (version `7.3.0`). Please confirm it is solved.  
And thank you for bringing it up, indeed I have to come up with some automation for publishing upon schema change.

**Comment by mattlewis92** [comment]
Nice, thanks so much for the fast response! Just tested and it works perfectly now 👍
