### ISSUE TITLE
Support for the latest architect API

### ISSUE THREAD

**Issue by mgechev** [meltedspark/angular-builders#227]
**Is your feature request related to a problem? Please describe.**

In Angular CLI we're working on the new architect API, which will not be completely backwards compatible with its old version.

**Describe the solution you'd like**

To not break existing projects using `angular-builders`, consider exploring the API changes from https://github.com/angular/angular-cli/pull/13463 and migrating the current builders to the latest primitives.

**Additional context**

If you think this would be helpful, we can share the design document of the new architect API. Alternatively, you can look at the existing builders.

Let me know how we can be most helpful!

**Comment by meltedspark** [comment]
Already on the Slack channel + have seen the design document. Waiting for beta to start working. But thanks for reaching out!

**Comment by mgechev** [comment]
@hansl was fast!

**Comment by meltedspark** [comment]
Yep indeed. I'm reopening it just for having it around for tracking the progress.
