### ISSUE TITLE
missing builder for :build

### ISSUE THREAD

**Issue by giniedp** [meltedspark/angular-builders#238]
I have added a library to an existing workspace (`ng generate library my-lib`) and wanted to prepend a webpack loader but there is no such builder for `@angular-builders/custom-webpack:build`

Is this feature missing or am i missing something?

**Comment by meltedspark** [comment]
It should be either `:browser`, `:server` or `:karma`, not `build`.

**Comment by giniedp** [comment]
The docs does not mention a setup of an app with an embedded library. Which would have a setup like this (shortened)

```json
{
  "projects": {
    "my-app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
          },
        },
      }
    },
    "my-lib": {
      "root": "projects/my-lib",
      "sourceRoot": "projects/my-lib/src",
      "projectType": "library",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/my-lib/tsconfig.lib.json",
            "project": "projects/my-lib/ng-package.json"
          }
        },
      }
    }
  },
  "defaultProject": "my-app"
}
```

Following the docs i have to replace the

`@angular-devkit/build-angular:browser` bulder

with the

`@angular-builders/custom-webpack:browser` builder

but there is no replacement for

`@angular-devkit/build-ng-packagr:build` builder.

If i naively use `@angular-builders/custom-webpack:browser` i get errors complaining about `Unknown option: '--project'`

**Comment by meltedspark** [comment]
Oh I see. `build-ng-packagr` is a different builder which is not supported currently.  
If you'd like to have it, please open a separate feature request.  
I'm going to go over all the builders anyways in the nearest future, to support Angular CLI 8. If it's not a big deal I'll sease the opportunity to implement the `build-ng-packagr` for `custom-webpack`.  
Of course you're more than welcome to submit a PR for this feature.

**Comment by giniedp** [comment]
thx for the clarification. I'm now diving into custom builders myself.

**Comment by thibaud-sanchez** [comment]
Nothing new about this ?
Got the same problem, need to use custom webpack for library and can't found other way..

**Comment by meltedspark** [comment]
Nope, didn't get any chance to work on this. You can open a feature request, this way it will enter ToDo list. PR is welcome as well.
