### ISSUE TITLE
jest: run single test

### ISSUE THREAD

**Issue by remkoboschker** [meltedspark/angular-builders#24]
How can I run a single test?

**Comment by meltedspark** [comment]
Currently I can provide you a workaround. In _angular.json_ in the builder options specify the name of the test suite and the test like this:
```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "testNamePattern=[Test suite] [test]": true
          }
        },
```
For example, if you have the following test suite:
```
describe('AppComponent', () => {
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
}
```
the configuration would be:
```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "testNamePattern=AppComponent should create the app": true
          }
        },
```

Now, I know it's annoying to change _angular.json_ every time you'd like to run another test, therefore in the next version you will be able to do that by running `ng test testNamePattern=AppComponent should create the app"`

**Comment by remkoboschker** [comment]
Good to know, thank you once again
