### ISSUE TITLE
Is it possible to replace a template string while running ng serve?

### ISSUE THREAD

**Issue by Hackysack** [meltedspark/angular-builders#241]
Hi and thanks for the awesome repo and all the examples!

I'd like to replace a template string during build. For the production build, I use an extra webpack-config like this:
```
module.exports = {
    plugins: [
        new ReplaceInFileWebpackPlugin([{
            dir: 'dist',
            test: /main.*\.js$/,
            rules: [
                {
                    search: '{{CURRENT_VERSION_HERE}}',
                    replace: 'NEW_VERSION_HERE'
                }
            ]
        }])
    ]
};
```
...and everything is fine and dandy :) Unfortunately, this behavior only works when compiling the final app bundle, not during development with `ng serve`, as the app is only generated in-memory.

Is it possible to get the same functionality during ng serve? Like hooking into an event on the underlying dev-server?

Thanks!

**Comment by meltedspark** [comment]
Have you tried using [`dev-server:generic`](https://github.com/meltedspark/angular-builders/tree/master/packages/dev-server) builder with the same extended config?

**Comment by Hackysack** [comment]
If I put the exact same config on the serve target that is on the build target:
```
        "serve": {
          "builder": "@angular-builders/dev-server:generic",
          "options": {
            "customWebpackConfig": {
              "path": "./build/extra-webpack.config.js",
              "mergeStrategies": {
                "module.rules": "prepend"
              }
            },
            "browserTarget": "avs-de-portal:build"
          },
```
`ng serve` fails with:
`Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).`

**Comment by meltedspark** [comment]
You're not supposed to use `customWebpackConfig` in `dev-server:generic`. `browserTarget` is [enough](https://github.com/meltedspark/angular-builders/tree/master/packages/dev-server#example).

**Comment by Hackysack** [comment]
Ok, got that - did I misinterpret your suggestion?

> Have you tried using [`dev-server:generic`](https://github.com/meltedspark/angular-builders/tree/master/packages/dev-server) builder with the same extended config?

**Comment by meltedspark** [comment]
@Hackysack Probably I didn't express myself clearly enough. What I meant is to use `dev-server:generic` while providing it with a `browserTarget` that itself uses `custom-webpack:browser`. Just like in the example I gave.  
Anyways, did it help, or there is still a problem?

**Comment by Hackysack** [comment]
I see :) I was already using the `@angular-builders/dev-server:generic` builder with the `browserTarget` config option on my `serve` target - so unfortunately, it does not work.

**Comment by meltedspark** [comment]
I see. As you correctly mentioned it is probably because `ng serve` serves the bundle from memory, while `ReplaceInFileWebpackPlugin` replaces strings in files that are not processed by any loaders (like assets that are just copied to `dist` folder).  
In your case (when `main.js` is obviously processed by loaders) I'd suggest you trying[ string-replace-webpack-plugin](https://www.npmjs.com/package/string-replace-webpack-plugin).  
Let me know how it all played out.

**Comment by Hackysack** [comment]
Thanks for your suggestion, I just tried it with the following config:
```
module.exports = {
    module: {
        rules: [{
            test: /main.*\.js$/,
            exclude: /node_modules/,
            use: StringReplacePlugin.replace({
                replacements: [{
                    pattern: '<%CURRENT_VERSION_HERE%>',
                    replacement: 'NEW_VERSION_HERE'
                }]
            })
        }]
    },
    plugins: [
        new StringReplacePlugin()
    ]
}
```
...which does not work, the string is not replaced :( 
Next, I tried to completely omit the `test: /main.*\.js$/,` option, which resulted in a bunch of errors:
```
ERROR in Module build failed (from ./node_modules/string-replace-webpack-plugin/loader.js):
TypeError: repl.replacement.bind is not a function
    at Object.<anonymous> (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:20:72)
    at Array.forEach (<anonymous>)
    at Object.module.exports (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:19:34)
ERROR in ./src/main.ts
Module build failed (from ./node_modules/string-replace-webpack-plugin/loader.js):
TypeError: repl.replacement.bind is not a function
    at Object.<anonymous> (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:20:72)
    at Array.forEach (<anonymous>)
    at Object.module.exports (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:19:34)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/string-replace-webpack-plugin/loader.js):
TypeError: repl.replacement.bind is not a function
    at Object.<anonymous> (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:20:72)
    at Array.forEach (<anonymous>)
    at Object.module.exports (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:19:34)
ERROR in ./src/sass/styles.scss
Module build failed (from ./node_modules/string-replace-webpack-plugin/loader.js):
TypeError: repl.replacement.bind is not a function
    at Object.<anonymous> (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:20:72)
    at Array.forEach (<anonymous>)
    at Object.module.exports (C:\myproject\node_modules\string-replace-webpack-plugin\loader.js:19:34)
```

I also experimented with setting `replaceDuplicatePlugins` in`angular.json` to true/false, but to no avail.

**Comment by meltedspark** [comment]
According to the docs of [`string-replace-webpack-plugin`](https://www.npmjs.com/package/string-replace-webpack-plugin)  `pattern` should be a regex, not a string like in your example and `replacement` should be an ECMAScript [string replacement function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter), not a string like in your example.

**Comment by Hackysack** [comment]
Oh man, I mixed up my arguments - I tried a few other string replacement plugins, some of which take `function | string` for the replacement value 😑 

It works now! Thanks for your patient help! 👍
