### ISSUE TITLE
Data path "" should have required property 'name' & @ionic/angular-toolkit

### ISSUE THREAD

**Issue by OCALAB** [meltedspark/angular-builders#242]
**Angular version:**
[x] **7.x**
**Ionic version:**
[x] **4.x**
**@angular-builders/custom-webpack version:**
[x] **7.3.1*

**Current behavior:**
Data path "" should have required property 'name' when using --livereload and a custom webpack.config

**Expected behavior:**
Is it possible to use a custom "**webpack.config.js**" without loosing livereload option?

Using the following configuration with the command "**ionic cordova run browser --livereload**" I receive the error: [**ng] Schema validation failed with the following errors: [ng] Data path "" should NOT have additional properties(customWebpackConfig).**

**Steps to reproduce:**
"ionic-cordova-serve": {
     "builder": "@ionic/angular-toolkit:cordova-serve",
     "options": {
          "cordovaBuildTarget": "app:ionic-cordova-build",
           "devServerTarget": "app:serve",
          "customWebpackConfig": {
               "path": "./config/webpack.config.js"
          }
     },
     "configurations": {
          "production": {
               "cordovaBuildTarget": "app:ionic-cordova-build:production",
               "devServerTarget": "app:serve:production"
          }
    }
}

**Comment by OCALAB** [comment]
inally I've got the solution. No need to use the customWebpackConfig package. Just put the webpack.config in the root project directory to merge it during the compile/transpile task!

**Comment by meltedspark** [comment]
I'm not sure I understand how it is related to the `angular-builders`. Does `@ionic/angular-toolkit:cordova-server` use `angular-builders` under the hood? Or am I missing something?
