### ISSUE TITLE
jest: breakpoints in vscode

### ISSUE THREAD

**Issue by remkoboschker** [meltedspark/angular-builders#25]
Has anyone managed to get breakpoints to work in vscode? I have the following launch config that works fine except for the breakpoinst not being hit. Is shows the right code fragments where an exception is raised or matcher fails. So I do not think it has something to do with source maps.

````
        {
            "name": "ng test",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/@angular/cli/bin/ng",
            "args": ["test"],
            "console": "integratedTerminal",
            "outFiles": ["${workspaceRoot}/output/debug/**/*"]
        }
````

**Comment by meltedspark** [comment]
Try adding `--inspect-brk` to the node `runtimeArgs` and `runInBand` for jest builder options.

**Comment by remkoboschker** [comment]
Thank you for your suggestion. The debugger seems to attach correctly without the extra ``runtimeArgs``. The ``runInBand`` did not help either. The output from the launch debugger command is shown below.
````
cd [path to workspace root] && "C:\Program Files\nodejs\node.exe" --inspect-brk=20693 node_modules\@angular\cli\bin\ng test --watch
Debugger listening on ws://127.0.0.1:20693/bb1874a6-c540-4295-8f57-44e6681d6ea8
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
````

**Comment by remkoboschker** [comment]
I found that breakpoints do work when I'm not running the tests in watch mode. Disabling watchMan by passing the ``--no-watchMan`` cli option does not help. I'm closing the issue, because it does not seem to be specific to this builders setup.

**Comment by michaeljota** [comment]
You can use this configuration to use VSCode debugger with Jest:

```json
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/@angular/cli/bin/ng",
        "test",
        "--runInBand",
        "--no-cache",
        "--env=jsdom"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "port": 9229
    }
```

Tested with Angular 6 and Jest 23.6

**Comment by michaeljota** [comment]
Being unable to debug in watch mode is a known bug from [Jest#6739](https://github.com/facebook/jest/issues/6739)
