### ISSUE TITLE
custom-webpack - Support for Angular CLI 7 

### ISSUE THREAD

**Issue by gustavomick** [meltedspark/angular-builders#250]
**Describe the bug**
Seems not to be working on angular cli 7.

Could  you confirm is cli 7 is supported? thanks

**Comment by meltedspark** [comment]
Yes, version 7 works with Angular CLI 7

**Comment by adamelliotfields** [comment]
Hi Evgeny,

Related to the current issue, I just started a fresh Angular 7 project and made the necessary changes to "build" and "serve" per the README.

I'm getting:

```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).
```

Is there any additional configuration that is required? Perhaps a member of the community that has it working can share some insight?

Thank you in advance.
