### ISSUE TITLE
webpack.config.js not found even if customWebpackConfig is not set

### ISSUE THREAD

**Issue by chaoyangnz** [meltedspark/angular-builders#251]
**Describe the bug**
I just want to merge extra webpack config for production build. So I only config the production options, but for development build, it runs into errors: `webpack.config.js not found`

**Builder:**
 - @angular-builders/custom-webpack
 - 7.3.1

**Libraries**
 - `angular-devkit/build-angular`: 0.12.3

**Expect**
Ignore when customWebpackConfig is not set

**Additional context**
My angular.json config is like
```
"build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist/mall/browser",
            "index": "projects/mall/src/index.html",
            "main": "projects/mall/src/main.ts",
            "polyfills": "projects/mall/src/polyfills.ts",
            "tsConfig": "projects/mall/tsconfig.app.json",
            "sourceMap": true,
            "assets": [
              "projects/mall/src/favicon.ico",
              "projects/mall/src/assets"
            ],
            "styles": [
              "projects/mall/src/styles.scss"
            ],
            "scripts": [],
            "statsJson": true
          },
          "configurations": {
            "production": {
              "customWebpackConfig": {
                "path": "extra-webpack.config.js",
                "mergeStrategies": { "devtool": "replace" }
              }
         }
```

**Comment by meltedspark** [comment]
Yeah, indeed a use case that I missed. You're welcome to PR (it's just adding a default value in schema).  
Meanwhile the workaround is to create an empty config for development and specify it in options.

**Comment by meltedspark** [comment]
@chaoyangnz Hey, I saw that you closed the pull request. Does that mean that you're off this task and I should take it myself? Just checking.

**Comment by chaoyangnz** [comment]
yes, please do

**Comment by chaoyangnz** [comment]
The issue is not fixed. I upgrade the version, the same error can be seen.

I checked your fix, the problem is when no extraWebpackConfig is specified, its value is not `undefined` or `null`, but ```
{
    path: undefined,
    mergeStrategies: {};
    replaceDuplicatePlugins: undefined;
}
```
that is why null guard is not sufficient.

Hope this helps.

**Comment by meltedspark** [comment]
Are you certain? Because there is an e2e test that passes (with unspecified value). Make sure the version you have is `7.4.2` and check out `sanity-app` in the examples.

**Comment by chaoyangnz** [comment]
I am sure. I download the `sanity-app` folder, change the version in `package.json` to 7.4.2.
then `yarn install`, `yarn run build`, you will see the error.

Why I said the default value is not `undefined` and `null`, that is because I debugged it when I created the pull request days ago.

> Are you certain? Because there is an e2e test that passes (with unspecified value). Make sure the version you have is `7.4.2` and check out `sanity-app` in the examples.

**Comment by meltedspark** [comment]
Changing version in _package.json_ alone won't help, because there is a _package-lock.json_. Please install the latest version by running `yarn add @angular-builders/custom-webpack@latest`. 
The default value is fine, it's `false` and not `null` or `undefined` so it works.

**Comment by chaoyangnz** [comment]
> Changing version in _package.json_ alone won't help, because there is a _yarn.lock_. Please install the latest version by running `yarn add @angular-builders/custom-webpack@latest`.
> The default value is fine, it's `false` and not `null` or `undefined` so it works.

The same following what you said. I even removed `yarn.lock`. 
The is the version from yarn.lock
`"@angular-builders/custom-webpack@^7.4.2":
  version "7.4.2"
  resolved "https://registry.yarnpkg.com/@angular-builders/custom-webpack/-/custom-webpack-7.4.2.tgz#3317440a8e833eff37df34792cda772c97a4d725"
  integrity sha512-+ZR7sDm1wLaOvR8giE+b/2FfUA4RL+Gz2q058ceVBjrPG41dTeh9orK8H1xATWuCkTcIvqxBUqVIZjGvsEdpwg==
  dependencies:
    lodash "^4.17.10"`


could you try yourself?

**Comment by meltedspark** [comment]
Yeah, you are right. Somehow the wrong _schema.json_ slipped into the build.
Will publish the correct one soon. 
Reopening meanwhile.

**Comment by meltedspark** [comment]
Would you mind trying version `7.4.3`?

**Comment by chaoyangnz** [comment]
> Would you mind trying version `7.4.3`?

Tried. it works. thanks
