### ISSUE TITLE
custom-webpack e2e tests broken

### ISSUE THREAD

**Issue by chaoyangnz** [meltedspark/angular-builders#255]
**Describe the bug**
I clone this repo, run `yarn install && yarn run e2e`, it fails with errors:
`
custom webpack server builder test › Should contain customWebpackConfig

    TypeError: Cannot read property 'properties' of undefined
`

**Screenshots**

**Builder:**
 - custom-webpack

**Additional context**
I checked the e2e tests like `packages/custom-webpack/e2e/custom-webpack-server-schema.spec.ts`, and found it requires `../src/server/schema.json` which is obviously not existing.

**Comment by meltedspark** [comment]
You should run `yarn build` before you run `e2e`.
Generally speaking the preferred way to build and run the whole project is with install and CI scripts like it is done in `.travis.yml`

**Comment by chaoyangnz** [comment]
Fine. but it is wried to depend on compiled file to run e2e.
