### ISSUE TITLE
jest: setting globals

### ISSUE THREAD

**Issue by remkoboschker** [meltedspark/angular-builders#26]
I think there might be a bug running a setup script.

I have a ``jest.config.js`` file in the root of my angular 6 project.
````
module.exports = {
    bail: true,
    verbose: false,
    setupFiles: ['./script-globals.js']
};
````
the ``script-globals.js`` file
````
global['$'] = 'barry';
````
yet in my test ``$`` and ``global.$`` are both undefined.

In the standard karma builder you can pass in a array of scripts to bundle. I would be nice if something similar were possible using this jest builder

**Comment by meltedspark** [comment]
If it's a single app project, _jest.config.js_ file should be in _src/_ directory and not in the root. If it is a multi-project then _jest.config.js_ shall sit at the root of the relevant project. Is this the case and it is still not working?

**Comment by remkoboschker** [comment]
Yes, I found it. Sorry, it is working now.  Thank you.
