### ISSUE TITLE
Angular 7 test files are ignored by default configuration

### ISSUE THREAD

**Issue by bcaure** [meltedspark/angular-builders#264]
**Describe the bug**
I know that Angular 6 CLI is pre-requisiten, but can you provide any workaround for Angular CLI 7 clean new app?
Currently test files are ignored, don't understand why:

```
> ng test

  22 files checked.
  testMatch: C:/projets/jest-angular-test/src/**\+(*.)+(spec|test).+(ts|js)?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 22 matches
  testRegex:  - 22 matches
Pattern:  - 0 matches

No tests found, exiting with code 1
```

(full trace below)

Same app setup with jest-preset-angular works fine: 

```
> jest

 PASS  src/app/app.component.spec.ts
  AppComponent
    √ should create the app (104ms)
    √ should have as title 'jest-angular-test-preset-angular' (65ms)
    √ should render title in a h1 tag (80ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
```

**To Reproduce**
1. npm install -g @angular/cli 
2. ng version

```Angular CLI: 7.3.5```

3. ng new jest-angular-test
4. npm i -D jest @angular-builders/jest
5. angular.json, replace test section by:

```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {}
        },
``` 
6. ng test

``` 
warning: unable to locate custom jest configuration file at path "C:\projets\jest-angular-test\src\jest.config.js"
● Deprecation Warning:

  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.

  Please update your configuration.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\projets\jest-angular-test
  22 files checked.
  testMatch: C:/projets/jest-angular-test/src/**\+(*.)+(spec|test).+(ts|js)?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 22 matches
  testRegex:  - 22 matches
Pattern:  - 0 matches

No tests found, exiting with code 1
``` 

**Builder:**
 - @angular-builders/jest
 - 7.3.1

**Libraries**
 - `angular-devkit/build-angular`: 0.13.5

**Additional context**
Windows 10
Angular CLI 7

**Comment by meltedspark** [comment]
Actually the latest version should work with Angular CLI 7, versions are aligned. If it doesn't it's certainly a bug. Would you mind giving a look to example applications and see if it helps you somehow to identify the root cause.  
On my side I'll try try it with a brand new NG app.

**Comment by meltedspark** [comment]
Ok so I gave it a look. I didn't manage to reproduce this issue. I did:
 - `ng new jest-app`
- `npm i -D jest @angular-builders/jest`
- change the test builder

You issue didn't come up but something else did. Apparently the version of `jest-preset-angular` that comes with `7.3.1` is not compatible with `jest@24.*`. 
So the tests failed with `Jest encountered an unexpected token`.  
Pinning Jest to `23.6` fixed the issue.  
Could you confirm that it fixes the issue on your side as well? As for the latest jest version [this](https://github.com/meltedspark/angular-builders/pull/246/files) PR should add a support.

**Comment by meltedspark** [comment]
Should put version constraint on `7.3.1` (`jest < 24`)

**Comment by bcaure** [comment]
Pinning Jest to 23.6 solved my problem. Thanks!
