### ISSUE TITLE
How to set options on loaders?

### ISSUE THREAD

**Issue by mcgraphix** [meltedspark/angular-builders#27]
I'm pretty sure this is a feature request, because the schema doesn't seem to allow this. Perhaps it is possible already and it just needs better documentation.

I would like to be able to set configure the options for the loaders used in the config. Specifically, I would like to add an attribute on the generated style tags. While the style-loader supports supplying attrs via the options, there doesn't seem to be a way to configure that.

**Comment by meltedspark** [comment]
If I understand correctly you'd like to add `options` object to and existing (Angularish) `style-loader`.  
In this case, would you mind trying a beta version `2.3.0-beta.1` and let me know if it works for you?

**Comment by mcgraphix** [comment]
@meltedspark sure. What would the syntax be to configure that via the extra webpack config file?

**Comment by meltedspark** [comment]
The regular syntax, just like it described in the [docs](https://webpack.js.org/concepts/loaders/).

**Comment by mcgraphix** [comment]
what I mean is, if I want to override the options for a specific loader, do I need to override the entire loader definition? For example, assuming that angular generates this loader for css files:

```
rules: [
            {
              test: /\.css$/,
              use: [
                 'style-loader',
                {loader: 'sass-loader'}
              ]
            },
          ]
```
and I want to add attributes to the 'style-loader', can I just do this:
```
rules: [
            {
              test: /\.css$/,
              use: [
                {loader: 'style-loader', options: {attrs: {'data-from-angular': 'true'}}}
              ]
            },
          ]
```
Or do I need to specify all the existing loaders even though I don't want to change anything about them?

**Comment by meltedspark** [comment]
It would be enough to modify this single loader.

**Comment by meltedspark** [comment]
@mcgraphix any updates?
