### ISSUE TITLE
Repo link in NPM is wrong

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [meltedspark/angular-builders#270]
**Describe the bug**

https://www.npmjs.com/package/@angular-builders/custom-webpack returns a 404 link

**Comment by meltedspark** [comment]
Thanks for reporting, will be fixed in the next version.

**Comment by JustAnotherSoftwareDeveloper** [comment]
Sweet. I know it's minor, but confused me when I was looking into a
different bug.
