### ISSUE TITLE
loaders are not loaded when building with aot 

### ISSUE THREAD

**Issue by sagi-levy-sp** [meltedspark/angular-builders#273]
Hi,
I tried to use custom-webpack-browser in order to apply a task on a build. 
The task should clean up certain attributes from our app html.
The process worked for me on ng build till I tried to use it on --prod ..

As far as I understand it seems like the build does not load the custom rule set to it, when building with AOT for prod. 

Any suggestions?
 
**To Reproduce**

on _**angular.json**_: 
`"architect": {
        "build": {
          "builder": "angular-cli-builders:custom-webpack-browser",
          "options": {
            "customWebpackConfig": {
              "path": "./webpack.extra.js",
              "mergeStrategies": {
                "externals": "append"
              }
            },`

**_webpack.extra.js_**:
var path =  require('path');
module.exports = (config) => {
  console.log (config.mode, __dirname);

  config.module.rules.push({
    test: /\.html$/,
    use: ['myLoader']
  });

  config.resolveLoader.alias = {'myLoader': path.join(__dirname,'my-loader.js')};
  return config;
};

**_my-loader.js_**
`module.exports = function myLoader(source) {
  console.log ('\myLoader is called\n');
  return source;
}`

execute ng build and it all good - loader is load and do its work.

**execute ng build --prod=true - loader is NOT loaded.**

**Expected behavior**
The loader should loaded on prod env

**Builder:**
@angular-builders/custom-webpack@7.4.3

Thanks you
Sagi

**Comment by joanllenas** [comment]
Hey @sagi-levy-sp did you find a solution? 
I'm facing the same problem. I want to remove `data-` attributes when releasing to production but it does not work in aot mode.

**Comment by just-jeb** [comment]
Try [disabling](https://github.com/just-jeb/angular-builders/issues/616#issuecomment-554356151) direct templates loading.

**Comment by joanllenas** [comment]
Thanks! that did the job.
