### ISSUE TITLE
Unable to add custom customWebpackConfig to "serve" configurations

### ISSUE THREAD

**Issue by ThisIsIvan** [meltedspark/angular-builders#286]
**Describe the bug**
I'm trying to define the customWebpackConfig within a target in the "serve" architect. 
Here is an abbreviated version of my angular.json.
```
         "architect": {
                "build": {
                    "builder": "@angular-builders/custom-webpack:browser",
[....]
                 "serve": {
                    "builder": "@angular-builders/dev-server:generic",
                    "options": {
                        "browserTarget": "myproject:build"
                    },
                    "configurations": {
                        "local": {
                            "customWebpackConfig": {
                                "path": "./build/webpack.config.local.js",
                                "mergeStrategies": {
                                    "module.rules": "replace"
                                }
                            }
                        },
```
As you can see I defined a target "local" in the configurations of the serve architect.  I always receive the error
`Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).`
The same error occurs if I define the customWebpackConfig within the options of my serve target, or within a target in the "build" architect.
Defining customWebpackConfig within the options of my "build" architect works.

**Builder:**
- "@angular-builders/custom-webpack": "^7.4.3",
- "@angular-builders/dev-server": "^7.3.1",

**Libraries**
 - "@angular-devkit/build-angular": "^0.13.7"
- "@angular/cli": "^7.3.7"
- "@angular/compiler-cli": "^7.2.11"

**Comment by meltedspark** [comment]
Please [notice](https://github.com/meltedspark/angular-builders/blob/master/packages/custom-webpack/README.md#custom-webpack-browser) that `customWebpackConfig` is an option of `@angular-builders/custom-webpack:browser` builder. Therefore it should be specified in `build` target and not `serve`. 
After you enabled custom webpack build you can use [dev-server:generic](https://github.com/meltedspark/angular-builders/blob/master/packages/dev-server/README.md#dev-server-generic) builder to enable it for `serve` as well. No special options are required for `serve` target - just replace the builder.

**Comment by ThisIsIvan** [comment]
Thank you for the quick response meltedspark!
As you can see from my snippet, I did define the custom-webpack builder for the `build` target.
I also have defined the `dev-server:generic` builder for the `serve` target.

Does that mean I can't define `customWebpackConfig` within a configuration of the `serve` target? 
And if not, is there a way to address a specific `build` configuration, when running `ng serve`?

**Comment by meltedspark** [comment]
Something like this should work:
```
         "architect": {
                "build": {
                    "builder": "@angular-builders/custom-webpack:browser",
                    [....]
                    "configurations": {
                        "local": {
                            "customWebpackConfig": {
                                "path": "./build/webpack.config.local.js",
                                "mergeStrategies": {
                                    "module.rules": "replace"
                                }
                            }
                        },
                 "serve": {
                    "builder": "@angular-builders/dev-server:generic",
                    "options": {
                        "browserTarget": "myproject:build"
                    },
                    "configurations": {
                       "local": {
                           "browserTarget": "myproject:build:local"   
                       }                    
                    }
```

You can see example (with different webpack configuration for `production` configuration) [here](https://github.com/meltedspark/angular-builders/blob/master/packages/custom-webpack/examples/append-webpack-plugins/angular.json).

**Comment by ThisIsIvan** [comment]
Ah I see. Thank you very much for your help!
