### ISSUE TITLE
[Migration] dev-server builder to v8 Builders API

### ISSUE THREAD

**Issue by gund** [meltedspark/angular-builders#317]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to serve dev server in angular v8 with `
@angular-builders/dev-server` builder in use.

**Describe the solution you'd like**
Will this builder be migrated to v8 Builders API any time soon?

As the `@angular-builders/custom-webpack` builder was already migrated for new v8 version.

Thanks

**Comment by meltedspark** [comment]
I wish all the issues were that easy to solve ))) 
The builder is now part of `@angular-builders/custom-webpack`.  
At this very time I'm working on updating the documentation. You can find the migration guide [here](https://github.com/meltedspark/angular-builders/blob/v8-migration-docs/MIGRATION.MD)

**Comment by ashutoshmittal2309** [comment]
@meltedspark Can you tell me which version of angular-builders has support for Angular CLI 8. I tried using v7 but it is not working.

"@angular-builders/custom-webpack": "^7.4.3",
    "@angular-builders/dev-server": "^7.3.1"

**Comment by ashutoshmittal2309** [comment]
Never mind, i didn't realized there is `next` version, seems to be working now.

**Comment by meltedspark** [comment]
I guess this issue can be closed? @gund

**Comment by gund** [comment]
Oh nice, I did not see it was deprecated.

Thanks for answer, I'm closing this issue.

**Comment by stephenasamoah** [comment]
> I wish all the issues were that easy to solve )))
> The builder is now part of `@angular-builders/custom-webpack`.
> At this very time I'm working on updating the documentation. You can find the migration guide [here](https://github.com/meltedspark/angular-builders/blob/v8-migration-docs/MIGRATION.MD)

Link seems to be broken at the moment

**Comment by just-jeb** [comment]
Fixed, thanks for heads up.
