### ISSUE TITLE
Pattern returns 0 matches

### ISSUE THREAD

**Issue by DmitryEfimenko** [meltedspark/angular-builders#32]
Doesn't find specs to run:
Below is the output

> C:\Source\my\website\projects\pwa/**/+(*.)+(spec|test).+(ts|js)?(x) - 0 matches

I think it might be an issue related to Windows. Notice the slashes.

**Comment by meltedspark** [comment]
Could you provide your _angular.json_, _package.json_ and _jest.config.js_ if exists?

**Comment by DmitryEfimenko** [comment]
looking at it made me realize it was a mistake on my part. Wrong configuration.
Closing.
