### ISSUE TITLE
custom-webpack package does not have dist folder (8.0.0)

### ISSUE THREAD

**Issue by linjie997** [meltedspark/angular-builders#323]
**Describe the bug**
After installing the latest 8.0.0 version of @angular-builders/custom-webpack, the package installed does not have the required folder /dist
The folder only contains: builders.json, LICENSE, package.json and README.md.
In fact, while trying to build the application, the cli gives the following error:
Cannot find module 'C:\{{dir}}\node_modules\@angular-builders\custom-webpack\dist\browser\schema.json'

I have tried to clean che npm cache and install it over again but the situation remains the same

**Comment by meltedspark** [comment]
Issue confirmed, on it.

**Comment by meltedspark** [comment]
@linjie997 @abadakhshan Please confirm the issue is solved with `8.0.1`

**Comment by linjie997** [comment]
I can confirm upgrading to 8.0.1 solves the issue.
Thank you.

**Comment by abadakhshan** [comment]
I upgrade "@angular-builders/custom-webpack" to 8.0.1
but I already have that problem
