### ISSUE TITLE
"ng serve and ng serve --prod" fails after adding and setting up custom-webpack

### ISSUE THREAD

**Issue by Lequoa** [meltedspark/angular-builders#328]
**Describe the bug**

I have set up a custom webpack, which runs well with custom-webpack:browser in the "standard" angular build target. Now I want to add custom webpack support to serve, so I've followed the example: [https://alligator.io/angular/custom-webpack-config/](url)

ng serve and ng build are both failing with the error `Schema validation failed with the following errors:
  Data path ".builders['browser']" should have required property 'class'.`

Maybe I'm just missing something small here, but I can't see what.

My files:
// extra-webpack.config.js  
```
const JoditPlugins = require('jodit');
module.exports = {
  plugins: [
    new JoditPlugins({
      keep_fnames: true
    })
  ]
}
```

//angular.json
```
"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "replaceDuplicatePlugins": true
            }
```
// package.json

```
"devDependencies": {
    "@angular-builders/custom-webpack": "8.0.0",
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/datatables.net": "^1.10.17",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.29",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jodit": "^3.2.44",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.12.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
```

Error while: `ng serve`: `Schema validation failed with the following errors:
  Data path ".builders['browser']" should have required property 'class'.`

**Comment by meltedspark** [comment]
You're using version 8 with Angular 7. You should be using version 7 for Angular 7 and version 8 for Angular 8. Also, when using version 8 use `8.0.1`

**Comment by Lequoa** [comment]
Thank you. Updated the version to 7. now it builds. ;)
