### ISSUE TITLE
Cannot find type definitions for jest

### ISSUE THREAD

**Issue by michaeljota** [meltedspark/angular-builders#334]
**Describe the bug**

After following the steps in [Readme](https://github.com/meltedspark/angular-builders/blob/master/packages/jest/README.md) TS is throwing as it can't find any of the global types.

**To Reproduce**
1. Create a new Angular CLI app (ng new app)
2. Add Jest as described in the Jest builder Readme
3. Update an spec to use a jest matcher, such as `resolve` for example. 
4. npm `ng test`
5. See error

**Example**

[jest-error.zip](https://github.com/meltedspark/angular-builders/files/3303539/jest-error.zip)

**Expected behavior**

There should be no errors.

**Builder:**
 - Jest builder
 - 8.0.2

**Libraries**
 - `angular-devkit/build-angular: ~0.800.0`: 

**Additional context**

<details>
<summary>
package.json
</summary>
<pre>
{
  "name": "jest-error",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-builders/jest": "^8.0.2",
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.8.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
</pre>
</details>

**Comment by meltedspark** [comment]
Can you elaborate please?
package.json, angular.json? tsconfig.json? 
Best way is to provide a minimal reproduction repo.

**Comment by michaeljota** [comment]
I made a zip, as a github repo is overkill for this. As you can see, it's a fresh Angular application with Angular CLI 8, with the Jest implemented as it's explained in the readme.

[jest-error.zip](https://github.com/meltedspark/angular-builders/files/3263155/jest-error.zip)

**Comment by michaeljota** [comment]
I also, updated the issue. Sorry for misfiled yesterday.

**Comment by meltedspark** [comment]
Ok, that's actually my bad. The README is not up to date.  
The root cause of this problem is that Jest@24 comes with built in types and while I removed the "install @types/jest" step from the setup steps I forgot to update the `tsconfig.json` section.  
Adding "types: ["jest"]" is what causes the issues. You can safely remove it from both tsconfigs (spec and root) and then you'll be able to use jest without `@types/jest`. Moreover I'd strongly advise you to remove it once you removed the `types` entry from tsconfigs, because this is an obsolete typing, for version 23.

**Comment by michaeljota** [comment]
Thanks! Will do.

**Comment by michaeljota** [comment]
After I update the files, and remove `@types/jest` the types are from Jasmine, and not from Jest. 
You have to import `jest` package from somewhere. I do use the `test.ts` file to setup some modules, so I update it with `import 'jest'` there. So, maybe that should be in the docs as well.

**Comment by meltedspark** [comment]
It shouldn't be this way, Jest should pick up the typing. How do you know the types are Jasmine's types?  
What happens if you remove `@types/jasmine`?

**Comment by michaeljota** [comment]
If you select a Jasmine/Jest symbol such as `describe` and choose to go to declaration, it will go to the `index.d.ts` in the `@types/jasmine` folder. Also, if you try to use any of the jest symbols, such as `jest.fn()` it will throw as it doesn't find the `jest` namespace. I haven't try to remove `@types/jasmine` but I did update the `types` configuration of the main `tsconfig.json` with an empty array, preventing the IDE to pick any of the `@types/...` types. It threw as it could find any definitions for the test functions (`describe`, `it`, etc...)

**Comment by meltedspark** [comment]
So you are talking about IDE issue, not test run? If you just run `ng test` without importing Jest do you get any errors?

**Comment by michaeljota** [comment]
Running `ng test` regardless the `jest` importing, TS is unable to find the `jest` types.

**Comment by meltedspark** [comment]
That's just weird. Have you removed the `types` array from tsconfig? Take a look at one of the [examples](https://github.com/meltedspark/angular-builders/tree/master/packages/jest/examples), in both examples `ng test` runs all the tests.

**Comment by michaeljota** [comment]
Seems to work now. Specs are throwing, but I'll check if there is a problem on my side. Thanks.

**Comment by meltedspark** [comment]
OK please let me know if it doesn't.

**Comment by michaeljota** [comment]
It didn't work, but seems another issue. I open a separate issue for that: #346

**Comment by meltedspark** [comment]
So this issue can be closed?

**Comment by michaeljota** [comment]
Yes. Thank you.

**Comment by michaeljota** [comment]
Sorry. But it seems like jest is actually running with jasmine types. :/.

**Comment by michaeljota** [comment]
I updated the main issue with a reproducible environment in a zip file.

**Comment by snebjorn** [comment]
I'm also having problems after the update.

When running `ng test` I'm getting these errors

> error TS2304: Cannot find name 'jest'.
> 
> jest.mock('src/app/omitted');
> 
> error TS2304: Cannot find name 'jest'.
> 
> jest.clearAllMocks();

and VS Code will have nothing to do with the `jest` global

Details here https://stackoverflow.com/questions/56663876/how-to-use-jest-mock-after-types-jest-is-removed-jest24

**Comment by meltedspark** [comment]
Ok, seems that my assumption about `@types/jest` being deprecated was wrong. Apparently there is still a need in this. I'm going to update the migration guide and the docs, meanwhile you can `npm install -D @types/jest`, get the `typeRoots` back and add `types: ["jest"]` to `tsconfig.json` and `tsconfig.spec.json`.

**Comment by snebjorn** [comment]
@meltedspark adding `typeRoots` doesn't seem necessary anymore.

My config files look like this now (incl the ng8 structure changes) and `ng test` runs and VS Code knows about the `jest` global.

**package.json**
```
"@angular-builders/jest": "^8.0.3",
"@types/jest": "^24.0.15",
"jest": "^24.8.0",
"jest-preset-angular": "^7.1.1",
"ts-jest": "^24.0.2",
```
**tsconfig.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "lib": ["es2018", "dom"],
    "types": ["jest"],
    "strict": true                     // note strict mode, this isn't default
  }
}
```
**tsconfig.spec.json**
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "allowJs": true
  },
  "files": ["src/polyfills.ts"],
  "include": ["src/**/*.spec.ts", "src/**/*.d.ts"]
}
```

**Comment by giggio** [comment]
I can confirm that we still need `@types/jest`, but no need to keep `typeRoots` or `types`.

By default `typeRoots` will look into `node_modules/@types` and much more. See the docs:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by michaeljota** [comment]
`types` is in deed necessary for the IDE to discriminate from the types it should actually look up. If you don't set it, the IDE will understand that you want to use types that you actually want to exclude.
