### ISSUE TITLE
Jest builder 8 forces me to move tsconfig.spec.json to root

### ISSUE THREAD

**Issue by monocl-oskar** [meltedspark/angular-builders#337]
**Describe the bug**
It's no big deal, but after updating `@angular-builders/jest` to `8.0.2` from `
^7.3.1`, I had to move `tsconfig.spec.json` from `src/` to `/`.

I have my `tsconfig.app.json` in `src/` so it feels a bit messy to move, and I'm wondering if it's a bug causing the change?

I can configure the jest config with `configPath` to `src/jest.config.js`. Is there some way to configure the `tsConfig` path as well?

**To Reproduce**
1. Start on 7 with `tsconfig.spec.json` in `src/`
2. Upgrade to 8
3. `Test suite failed to run` `File not found: /Users/<redacted>/tsconfig.spec.json (resolved as: /Users/<redacted>/tsconfig.spec.json)` (File is at `<redacted>/src/tsconfig.spec.json`)

**Expected behavior**
Being able to specify where my `tsconfig.spec.json` is, I guess. Or just have the ability to have it in a subdir.

**Builder:**
`@angular-builders/jest 8.0.2`

**Libraries**
 - `@angular-devkit/build-angular`: `0.800.2`

**Comment by meltedspark** [comment]
Most probably something went wrong when you upgraded your Angular app. In Angular 8 (and I'm pretty sure in Angular 7 as well) all the tsconfigs are located under the root directory and the `/src` directory. You can verify that by generating a new app with `ng new`.  
Jest builder is designed to support the official Angular app file structure hence the change.

**Comment by monocl-oskar** [comment]
Thanks!

>hence the change.

Should I interpret this as: It was a change, and it was intended?

I understand that you want to go with the official Angular app file structure, the files in my project were added to `src/` before I came into it so I don't know why they were there.

**Comment by meltedspark** [comment]
I meant that the files from `src` directory should have been moved automatically during `ng upgrade`. Apparently in your case it didn't happen for some reason. But the best thing for you is to move them either way, because this is the file structure in Angular 8.  
But you're right that I probably have to provide an option to specify `tsConfig` path in builder options, just like in Karma builder. Will open a separate issue for this.
