### ISSUE TITLE
setupFilesAfterEnv property cannot be set. 

### ISSUE THREAD

**Issue by michaeljota** [meltedspark/angular-builders#346]
**Describe the bug**

If I set the `setupFilesAfterEnv` property in `jest.config.js`, the test will start throwing with random errors.

**To Reproduce**
1. Setup Jest as is in readme.
2. Add `setupFilesAfterEnv` property pointing to a file. 

Repo:
[jest-error.zip](https://github.com/meltedspark/angular-builders/files/3303407/jest-error.zip)

**Expected behavior**

No errors should be throw. 

**Builder:**
 - Jest builder
 - version: 8.0.2

**Libraries**
 - `angular-devkit/build-angular`: ~0.800.0

**Comment by michaeljota** [comment]
Seems to be about how lodash does the merging with merge function, as it doesn't concat arrays. lodash/lodash#2872. Maybe we could update this to concat the arrays values in the configurations by using mergeWith as the issue suggest?

**Comment by meltedspark** [comment]
Interesting... I was sure I fixed this issue a long time ago. Would you mind checking if the issue exists on latest 7 version? It also supports Jest 24, probably I screwed something during transition to version 8...

**Comment by michaeljota** [comment]
[jest-error-v7.zip](https://github.com/meltedspark/angular-builders/files/3306971/jest-error-v7.zip)

The error does reproduce in 7.4.4, with Angular CLI 7. (I setup a different environment as v7 only works with Angular 7).

**Comment by meltedspark** [comment]
Well, you are right then, we should use `mergeWith`. Would you like to issue a PR? If yes, please bear in mind it should include at least unit test, but ideally unit test and e2e test.

**Comment by michaeljota** [comment]
I modify the file locally. I'll try to make the PR, but I make no promises. However, with this changes the builder was able to load a file through the `setupFilesAfterEnv` property. 

```ts
function concatArrayProperties(objValue: unknown, srcValue: unknown) {
  if (Array.isArray(objValue)) {
    if (Array.isArray(srcValue)) {
      return objValue.concat(srcValue);
    }
    // This will make Jest to throw, as it is expecting an array, instead of silently fail.
    return srcValue;
  }
}

export const buildConfiguration = (defaultConfigResolver: DefaultConfigResolver,
  customConfigResolver: CustomConfigResolver) => 
  (projectRoot: Path,workspaceRoot: Path, configPath: string = 'jest.config.js') => {
    const globalDefaultConfig = defaultConfigResolver.resolveGlobal();
    const projectDefaultConfig = defaultConfigResolver.resolveForProject(projectRoot);
    const globalCustomConfig = customConfigResolver.resolveGlobal(workspaceRoot);
    const projectCustomConfig = customConfigResolver.resolveForProject(projectRoot, configPath);

    return mergeWith(globalDefaultConfig, projectDefaultConfig, globalCustomConfig, projectCustomConfig, concatArrayProperties);
}

export class JestConfigurationBuilder {

  constructor(private defaultConfigResolver: DefaultConfigResolver,
              private customConfigResolver: CustomConfigResolver) {
  }

  buildConfiguration(projectRoot: Path, workspaceRoot: Path, configPath: string = 'jest.config.js'): any {
    const pathToProject: Path = resolve(workspaceRoot, projectRoot);

    const globalDefaultConfig = this.defaultConfigResolver.resolveGlobal();
    const projectDefaultConfig = this.defaultConfigResolver.resolveForProject(pathToProject);
    const globalCustomConfig = this.customConfigResolver.resolveGlobal(workspaceRoot);
    const projectCustomConfig = this.customConfigResolver.resolveForProject(pathToProject, configPath);

    return mergeWith(globalDefaultConfig, projectDefaultConfig, globalCustomConfig, projectCustomConfig, concatArrayProperties);
  }
}
```

Also, locally I update the method `JestConfigurationBuilder#buildConfiguration` to use the `buildConfiguration` function, as: 

```ts
export class JestConfigurationBuilder {

  constructor(private defaultConfigResolver: DefaultConfigResolver,
              private customConfigResolver: CustomConfigResolver) {
  }

  buildConfiguration(projectRoot: Path, workspaceRoot: Path, configPath: string = 'jest.config.js'): any {
    const pathToProject: Path = resolve(workspaceRoot, projectRoot);
    return buildConfiguration(this.defaultConfigResolver, this.customConfigResolver)(
        pathToProject,
        workspaceRoot,
        configPath,
      );
  }
}
```

**Comment by meltedspark** [comment]
Actually I'm not sure we need to do that for all the arrays. `setupFilesAfterEnv` is a special case, because there is a built in setup that has to run and the user might want to provide one on top of it.  
However, what if the user would like to override `testMatch` property (to match a different test pattern in a specific project)? With this behavior it will merge it with the [default `testMatch` array](https://github.com/meltedspark/angular-builders/blob/master/packages/jest/src/default-config.resolver.ts#L20) and will still match the old pattern.

**Comment by meltedspark** [comment]
@michaeljota Btw, just figured out why I thought it was solved. There was another [issue](https://github.com/meltedspark/angular-builders/issues/193) where I provided a workaround. The same workaround should work for you as well. I think it's better than locally modifying source code of the builder.

**Comment by michaeljota** [comment]
I update the code just to see if it would work, but I could use your workaround.

What do you think about having a whitelist of properties that we know we need to concat? That way we only have to concat the properties we would use. However, I don't think that mergeWith currently support having the property as a parameter.

**Comment by michaeljota** [comment]
Seems like it's third argument it's the property name, so a whitelist would be a good way to go. If you are OK with it, I can send the PR later.

**Comment by michaeljota** [comment]
@meltedspark do you think we can backport this to the 7.4.x branch? In my team we are still using Angular 7, _but we are soon to upgrade_™. Meanwhile, we could use this in the 7.4.x, as anyone using that branch as it support Jest 24.

**Comment by meltedspark** [comment]
Sure, the fix is the same I guess.

**Comment by michaeljota** [comment]
Hey @just-jeb How are you? At the end I updated the application. Still, would be a nice feature to have this backported. I try to do it with a cherry pick, but seems that the code is not compatible. Anyway, do you think this fix can be in a new release? To update the version of this and setting the test. Thanks.

**Comment by just-jeb** [comment]
The code is not compatible indeed, should be much easier to reimplement it rather than cherry picking. I guess it will take you a few minutes since you've already implemented this in v8.  
As for v8 patch, yes it will be a part of the next release (most probably coming out this week).
