### ISSUE TITLE
Jest Custom Reporter Configuration Error

### ISSUE THREAD

**Issue by themounthead** [meltedspark/angular-builders#40]
I'm having some trouble adding a custom reporter such as 'jest-tap-reporter' to an Angular 6.0.1 project. The angular.json setting is as below

`
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "verbose": false,
            "noStackTrace": true,
            "silent": true,
            "colors": true,
            "reporters": "jest-tap-reporter",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        }
`
#### Error Report
_Could not resolve a module for a custom reporter. Module name: 'jest-tap-reporter'_.

It looks like the builder is unable to locate the module location. I tried the following but still get the above error -
- prefixed 'node_modules' to the module name
- checked the **rootDir** value from the  `ng test--showConfig` output and its pointing to the correct Project directory

I've also enclosed the module name, like so, `["jest-tap-reporter"]` ; this time surprisingly no error, but I get the default output instead of the custom reporter's format.

Its worth noting that directly invoking jest (global), the reporter works as expected.

Am I missing something specific to the angular setup ? Please advise.

**Comment by meltedspark** [comment]
Which version are you using? It would be nice to have a repo with a minimal reproduction case so that I could take a look.

**Comment by themounthead** [comment]
@meltedspark thanks for your reply. I've created a simple [repo](https://github.com/themounthead/jest-custom-reporter-sandbox) that illustrates the problem. Hopefully it should help you analyze the issue. The Custom Reporter I've included is [jest-tap-reporter](https://github.com/MailOnline/jest-tap-reporter).

**Comment by meltedspark** [comment]
Indeed there is some problem with reporters provided via CLI arguments. Requires a more thorough investigation.  
Meanwhile you can define it in jest configuration - for example, to apply this reporter to all the projects in your workspace add the following to your _package.json_:
```js
  "jest": {
    "reporters": ["jest-tap-reporter"]
  },
```

Read more [here](https://github.com/meltedspark/angular-builders/tree/master/packages/jest#builder-options) if you want to apply this configuration for a single project or keep this configuration inside a separate file (not _package.json_).

**Comment by meltedspark** [comment]
Caused by #41
