### ISSUE TITLE
dev-server:generic doesn't seem to load custom webpack config

### ISSUE THREAD

**Issue by pj035** [meltedspark/angular-builders#76]
I have set up a custom webpack, which runs well with `custom-webpack:browser` in the "standard" angular `build` target. Now I want to add custom webpack support to `serve`, so I've followed the example https://github.com/meltedspark/angular-builders/tree/master/packages/dev-server.

It seems that my custom webpack is **not** loaded while running `ng serve`. Nonetheless `ng build` is working fine. For a brief test I have added a small `console.log` to my webpack config, which is only triggered on `ng build`.

Maybe I'm just missing something small here, but I can't see what.

My files:
```js
// webpack.config.js
console.log("webpack config")

exports = module.exports = {
  node : {
    crypto: true,
  },
};
```
// angular.json
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "projects": {
    "my-project": {
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist/my-project",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            }
          }
        },
        "serve": {
          "builder": "@angular-builders/dev-server:generic",
          "options": {
            "browserTarget": "my-project:build"
          }
        }
}
```
// package.json
```json
{
  ...
  devDependencies: {
    "@angular-builders/custom-webpack": "^2.4.1",
    "@angular-builders/dev-server": "^2.2.3",
    "@angular-devkit/architect": "^0.8.3",
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular-devkit/core": "^0.8.3",
    "@angular/cli": "~6.0.3",
   ....
  }
}
```

Error while `ng serve`: `ERROR in ./node_modules/aws4/aws4.js Module not found: Error: Can't resolve 'crypto'`

**Comment by meltedspark** [comment]
It might happen because of non-aligned versions of `@angular-devkit` packages (your  `@angular-devkit/build-angular` version is `~0.6.3` and the required is `>=0.7.0`)
Try the following:
1. `npm remove @angular-devkit/architect @angular-devkit/build-angular @angular-devkit/core`
2. `npm i -D @angular-devkit/build-angular@0.7` (`architect` and `core` are coming with `build-angular` so no need to specify them explicitly)

**Comment by pj035** [comment]
Thanks for the quick response. Initially I've checked for the prerequisites (version >= 0.7.0), but I guess due to `architect` and `core` having version `0.8.3` I misread the version of `build-angular` - `0.6.3` looks pretty similar in my editor's font size.

Anyways, updating `@angular-devkit/build-angular` has solved my problem.
