### ISSUE TITLE
using angular and typeorm

### ISSUE THREAD

**Issue by aammfe** [meltedspark/angular-builders#83]
Hello!!

I m trying to integrate typeorm in angular but unable due to ngcli limitation.
I have followed [this](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack) documentation but could not make it work with typeorm.

still getting 
![image](https://user-images.githubusercontent.com/11896817/46380251-121eea00-c6bb-11e8-88ed-fdbb90085190.png)

errors 

[repo](https://github.com/aammfe/Angular-6-with-Typeorm-not-working) where you can see issue.
this is [webconfig](https://github.com/aammfe/Angular-6-with-Typeorm-not-working/blob/master/webpack.config.js) and this is [angular.json](https://github.com/aammfe/Angular-6-with-Typeorm-not-working/blob/master/angular.json) 

please help.

**Comment by meltedspark** [comment]
From what I can see you haven't replaced `angular-devkit` builders with `@angular-builders/custom-webpack` in `angular.json`.

**Comment by aammfe** [comment]
sorry its working now :)
