### ISSUE TITLE
transformIgnorePatterns and transform options are being ignored for third party library

### ISSUE THREAD

**Issue by edwinabt** [meltedspark/angular-builders#85]
Hi, this is a sample repo with the problem happening:

[https://github.com/edwinabt/abt-jest-ng-app](https://github.com/edwinabt/abt-jest-ng-app)

Run the regular Angular steps to run an app:

- npm install
- ng serve
- go to http://localhost:4200
- inspect the console, you should see, **Yes, Google API loaded**, it means the third party library, **ng-gapi**, loaded fine:
![image](https://user-images.githubusercontent.com/9532300/46432119-6fe31e80-c71b-11e8-92ea-4144c76ec715.png)

Now, the problem is with a library called **ng-gapi** that wraps the Google API SDK to be used in angular. When you run **ng test** it reports the test failed because of **Jest encountered an unexpected token**. I've read about this problem and tried the possible solutions, but, none are working for me. 

![image](https://user-images.githubusercontent.com/9532300/46432558-8ccc2180-c71c-11e8-9bcb-3f5ce0bcf258.png)

Is this a bug? or I am doing something wrong?

**Comment by meltedspark** [comment]
From a quick Googling I found the most probable candidate for the source of the problem.  
From you screenshot I can see that the library you use is compiled to ES6 modules, while you're using `commonjs` modules.  
This means that ES6 syntax is not recognized by jest and it has to be transpiled to `commonjs`.  
[Here](https://github.com/kulshekhar/ts-jest/issues/213) is the similar issue in `ts-jest`.

**Comment by edwinabt** [comment]
@meltedspark thanks... will take a look at that.

**Comment by meltedspark** [comment]
Could you create a repository with a minimal reproduction?

**Comment by meltedspark** [comment]
@jusefb That is great, thanks for sharing! I'm thinking of creating a section for frequent problems in the readme. Would you mind issuing a PR for that?

**Comment by jusefb** [comment]
Sure, never done it before :) will you need to create the section first?

**Comment by meltedspark** [comment]
You are welcome to create it yourself.
