### ISSUE TITLE
custom-webpack:karma javascript not in package

### ISSUE THREAD

**Issue by njirem** [meltedspark/angular-builders#96]
**Describe the bug**
When using the "@angular-builders/custom-webpack:karma" builder in `angular.json`. I get the error:
`Cannot find module '<root-dir>/node_modules/@angular-builders/custom-webpack/src/karma'`.
Which is correct, because the installed dependency does have a `karma` folder, but it only has a `schema.json`, but not an `index.js`.

**To Reproduce**
It is easily reproduced by creating a new angular project and using the "@angular-builders/custom-webpack:karma" as test builder in the `angular.json`.

**Expected behavior**
I would expect the file to be included in the package.

**Builder:**
 - @angular-builders/custom-webpack:karma
 - 2.5.3

**Libraries**
 - `angular-devkit/build-angular`: 0.9.0-rc.0

**Comment by njirem** [comment]
It seems the file isn't included in the compilation, because it isn't imported.

**Comment by meltedspark** [comment]
Should be fixed in `2.5.4`. Could you confirm that?
